export const imageMappings = {
    'Low Voltage': {
      'Cores' : {
        '1' : {
          '1mm': require('./../assets/Cables/Low-Voltage/Cores/1/1mm.png'),
          '1.5mm': require('./../assets/Cables/Low-Voltage/Cores/1/4mm.png'),
          '2mm': require('./../assets/Cables/Low-Voltage/Cores/1/7mm.png'),
          '4mm': require('./../assets/Cables/Low-Voltage/Cores/1/16mm.png'),
          '6mm': require('./../assets/Cables/Low-Voltage/Cores/1/1mm.png'),
          '10mm': require('./../assets/Cables/Low-Voltage/Cores/1/4mm.png'),
          '16mm': require('./../assets/Cables/Low-Voltage/Cores/1/7mm.png'),
          '25mm': require('./../assets/Cables/Low-Voltage/Cores/1/16mm.png'),
          '35mm': require('./../assets/Cables/Low-Voltage/Cores/1/1mm.png'),
          '50mm': require('./../assets/Cables/Low-Voltage/Cores/1/4mm.png'),
          '70mm': require('./../assets/Cables/Low-Voltage/Cores/1/7mm.png'),
        },
        '2' : {
          '1mm': require('./../assets/Cables/Low-Voltage/Cores/2/1mm.png'),
          '1.5mm': require('./../assets/Cables/Low-Voltage/Cores/2/4mm.png'),
          '2mm': require('./../assets/Cables/Low-Voltage/Cores/2/7mm.png'),
          '4mm': require('./../assets/Cables/Low-Voltage/Cores/2/16mm.png'),
          '6mm': require('./../assets/Cables/Low-Voltage/Cores/2/1mm.png'),
          '10mm': require('./../assets/Cables/Low-Voltage/Cores/2/4mm.png'),
          '16mm': require('./../assets/Cables/Low-Voltage/Cores/2/7mm.png'),
          '25mm': require('./../assets/Cables/Low-Voltage/Cores/2/16mm.png'),
          '35mm': require('./../assets/Cables/Low-Voltage/Cores/2/1mm.png'),
          '50mm': require('./../assets/Cables/Low-Voltage/Cores/2/4mm.png'),
          '70mm': require('./../assets/Cables/Low-Voltage/Cores/2/7mm.png'),
        },
        '3' : {
          '1mm': require('./../assets/Cables/Low-Voltage/Cores/3/1mm.png'),
          '1.5mm': require('./../assets/Cables/Low-Voltage/Cores/3/4mm.png'),
          '2mm': require('./../assets/Cables/Low-Voltage/Cores/3/7mm.png'),
          '4mm': require('./../assets/Cables/Low-Voltage/Cores/3/16mm.png'),
          '6mm': require('./../assets/Cables/Low-Voltage/Cores/3/1mm.png'),
          '10mm': require('./../assets/Cables/Low-Voltage/Cores/3/4mm.png'),
          '16mm': require('./../assets/Cables/Low-Voltage/Cores/3/7mm.png'),
          '25mm': require('./../assets/Cables/Low-Voltage/Cores/3/16mm.png'),
          '35mm': require('./../assets/Cables/Low-Voltage/Cores/3/1mm.png'),
          '50mm': require('./../assets/Cables/Low-Voltage/Cores/3/4mm.png'),
          '70mm': require('./../assets/Cables/Low-Voltage/Cores/3/7mm.png'),
        },
        '4' : {
          '10mm': require('./../assets/Cables/Low-Voltage/Cores/4/4mm.png'),
          '16mm': require('./../assets/Cables/Low-Voltage/Cores/4/7mm.png'),
          '25mm': require('./../assets/Cables/Low-Voltage/Cores/4/16mm.png'),
          '35mm': require('./../assets/Cables/Low-Voltage/Cores/4/1mm.png'),
          '50mm': require('./../assets/Cables/Low-Voltage/Cores/4/4mm.png'),
          '70mm': require('./../assets/Cables/Low-Voltage/Cores/4/7mm.png'),
          '95mm': require('./../assets/Cables/Low-Voltage/Cores/4/16mm.png'),
          '120mm': require('./../assets/Cables/Low-Voltage/Cores/4/1mm.png'),
          '150mm': require('./../assets/Cables/Low-Voltage/Cores/4/4mm.png'),
          '185mm': require('./../assets/Cables/Low-Voltage/Cores/4/7mm.png'),
        },
        '5' : {
          '2mm': require('./../assets/Cables/Low-Voltage/Cores/5/4mm.png'),
          '4mm': require('./../assets/Cables/Low-Voltage/Cores/5/7mm.png'),
          '6mm': require('./../assets/Cables/Low-Voltage/Cores/5/16mm.png'),
          '10mm': require('./../assets/Cables/Low-Voltage/Cores/5/1mm.png'),
          '16mm': require('./../assets/Cables/Low-Voltage/Cores/5/4mm.png'),
          '25mm': require('./../assets/Cables/Low-Voltage/Cores/5/7mm.png'),
          '35mm': require('./../assets/Cables/Low-Voltage/Cores/5/16mm.png'),
          '50mm': require('./../assets/Cables/Low-Voltage/Cores/5/1mm.png'),
          '70mm': require('./../assets/Cables/Low-Voltage/Cores/5/4mm.png'),
          '95mm': require('./../assets/Cables/Low-Voltage/Cores/5/7mm.png'),
          '120mm': require('./../assets/Cables/Low-Voltage/Cores/5/1mm.png'),
        },
        '6' : {
          '1mm': require('./../assets/Cables/Low-Voltage/Cores/6/1mm.png'),
          '1.5mm': require('./../assets/Cables/Low-Voltage/Cores/6/4mm.png'),
          '2mm': require('./../assets/Cables/Low-Voltage/Cores/6/7mm.png'),
          '4mm': require('./../assets/Cables/Low-Voltage/Cores/6/16mm.png'),
          '6mm': require('./../assets/Cables/Low-Voltage/Cores/6/7mm.png'),
          '10mm': require('./../assets/Cables/Low-Voltage/Cores/6/16mm.png'),
        },
        '7' : {
          '1mm': require('./../assets/Cables/Low-Voltage/Cores/7/1mm.png'),
          '1.5mm': require('./../assets/Cables/Low-Voltage/Cores/7/4mm.png'),
          '2mm': require('./../assets/Cables/Low-Voltage/Cores/7/7mm.png'),
          '4mm': require('./../assets/Cables/Low-Voltage/Cores/7/16mm.png'),
          '6mm': require('./../assets/Cables/Low-Voltage/Cores/7/7mm.png'),
          '10mm': require('./../assets/Cables/Low-Voltage/Cores/7/16mm.png'),
        },
      },
      // Add more suboptions here as needed
      '1mm': require('./../assets/Cables/Low-Voltage/1mm.png'),
      '4mm': require('./../assets/Cables/Low-Voltage/4mm.png'),
      '7mm': require('./../assets/Cables/Low-Voltage/7mm.png'),
      '16mm': require('./../assets/Cables/Low-Voltage/16mm.png'),
    },
    'Mid Voltage': {
      'Cores' : {
        '1' : {
          '1mm': require('./../assets/Cables/Mid-Voltage/Cores/1/1mm.png'),
          '1.5mm': require('./../assets/Cables/Mid-Voltage/Cores/1/4mm.png'),
          '2mm': require('./../assets/Cables/Mid-Voltage/Cores/1/7mm.png'),
          '4mm': require('./../assets/Cables/Mid-Voltage/Cores/1/16mm.png'),
          '6mm': require('./../assets/Cables/Mid-Voltage/Cores/1/1mm.png'),
          '10mm': require('./../assets/Cables/Mid-Voltage/Cores/1/4mm.png'),
          '16mm': require('./../assets/Cables/Mid-Voltage/Cores/1/7mm.png'),
          '25mm': require('./../assets/Cables/Mid-Voltage/Cores/1/16mm.png'),
          '35mm': require('./../assets/Cables/Mid-Voltage/Cores/1/1mm.png'),
          '50mm': require('./../assets/Cables/Mid-Voltage/Cores/1/4mm.png'),
          '70mm': require('./../assets/Cables/Mid-Voltage/Cores/1/7mm.png'),
        },
        '2' : {
          '1mm': require('./../assets/Cables/Mid-Voltage/Cores/2/1mm.png'),
          '1.5mm': require('./../assets/Cables/Mid-Voltage/Cores/2/4mm.png'),
          '2mm': require('./../assets/Cables/Mid-Voltage/Cores/2/7mm.png'),
          '4mm': require('./../assets/Cables/Mid-Voltage/Cores/2/16mm.png'),
          '6mm': require('./../assets/Cables/Mid-Voltage/Cores/2/1mm.png'),
          '10mm': require('./../assets/Cables/Mid-Voltage/Cores/2/4mm.png'),
          '16mm': require('./../assets/Cables/Mid-Voltage/Cores/2/7mm.png'),
          '25mm': require('./../assets/Cables/Mid-Voltage/Cores/2/16mm.png'),
          '35mm': require('./../assets/Cables/Mid-Voltage/Cores/2/1mm.png'),
          '50mm': require('./../assets/Cables/Mid-Voltage/Cores/2/4mm.png'),
          '70mm': require('./../assets/Cables/Mid-Voltage/Cores/2/7mm.png'),
        },
        '3' : {
          '1mm': require('./../assets/Cables/Mid-Voltage/Cores/3/1mm.png'),
          '1.5mm': require('./../assets/Cables/Mid-Voltage/Cores/3/4mm.png'),
          '2mm': require('./../assets/Cables/Mid-Voltage/Cores/3/7mm.png'),
          '4mm': require('./../assets/Cables/Mid-Voltage/Cores/3/16mm.png'),
          '6mm': require('./../assets/Cables/Mid-Voltage/Cores/3/1mm.png'),
          '10mm': require('./../assets/Cables/Mid-Voltage/Cores/3/4mm.png'),
          '16mm': require('./../assets/Cables/Mid-Voltage/Cores/3/7mm.png'),
          '25mm': require('./../assets/Cables/Mid-Voltage/Cores/3/16mm.png'),
          '35mm': require('./../assets/Cables/Mid-Voltage/Cores/3/1mm.png'),
          '50mm': require('./../assets/Cables/Mid-Voltage/Cores/3/4mm.png'),
          '70mm': require('./../assets/Cables/Mid-Voltage/Cores/3/7mm.png'),
        },
        '4' : {
          '10mm': require('./../assets/Cables/Mid-Voltage/Cores/4/4mm.png'),
          '16mm': require('./../assets/Cables/Mid-Voltage/Cores/4/7mm.png'),
          '25mm': require('./../assets/Cables/Mid-Voltage/Cores/4/16mm.png'),
          '35mm': require('./../assets/Cables/Mid-Voltage/Cores/4/1mm.png'),
          '50mm': require('./../assets/Cables/Mid-Voltage/Cores/4/4mm.png'),
          '70mm': require('./../assets/Cables/Mid-Voltage/Cores/4/7mm.png'),
          '95mm': require('./../assets/Cables/Mid-Voltage/Cores/4/16mm.png'),
          '120mm': require('./../assets/Cables/Mid-Voltage/Cores/4/1mm.png'),
          '150mm': require('./../assets/Cables/Mid-Voltage/Cores/4/4mm.png'),
          '185mm': require('./../assets/Cables/Mid-Voltage/Cores/4/7mm.png'),
        },
        '5' : {
          '2mm': require('./../assets/Cables/Mid-Voltage/Cores/5/1mm.png'),
          '4mm': require('./../assets/Cables/Mid-Voltage/Cores/5/7mm.png'),
          '6mm': require('./../assets/Cables/Mid-Voltage/Cores/5/16mm.png'),
          '10mm': require('./../assets/Cables/Mid-Voltage/Cores/5/1mm.png'),
          '16mm': require('./../assets/Cables/Mid-Voltage/Cores/5/4mm.png'),
          '25mm': require('./../assets/Cables/Mid-Voltage/Cores/5/7mm.png'),
          '35mm': require('./../assets/Cables/Mid-Voltage/Cores/5/16mm.png'),
          '50mm': require('./../assets/Cables/Mid-Voltage/Cores/5/1mm.png'),
          '70mm': require('./../assets/Cables/Mid-Voltage/Cores/5/4mm.png'),
          '95mm': require('./../assets/Cables/Mid-Voltage/Cores/5/7mm.png'),
          '120mm': require('./../assets/Cables/Mid-Voltage/Cores/5/1mm.png'),
        },
        '6' : {
          '1mm': require('./../assets/Cables/Mid-Voltage/Cores/6/1mm.png'),
          '1.5mm': require('./../assets/Cables/Mid-Voltage/Cores/6/4mm.png'),
          '2mm': require('./../assets/Cables/Mid-Voltage/Cores/6/7mm.png'),
          '4mm': require('./../assets/Cables/Mid-Voltage/Cores/6/16mm.png'),
          '6mm': require('./../assets/Cables/Mid-Voltage/Cores/6/7mm.png'),
          '10mm': require('./../assets/Cables/Mid-Voltage/Cores/6/16mm.png'),
        },
        '7' : {
          '1mm': require('./../assets/Cables/Mid-Voltage/Cores/7/1mm.png'),
          '1.5mm': require('./../assets/Cables/Mid-Voltage/Cores/7/4mm.png'),
          '2mm': require('./../assets/Cables/Mid-Voltage/Cores/7/7mm.png'),
          '4mm': require('./../assets/Cables/Mid-Voltage/Cores/7/16mm.png'),
          '6mm': require('./../assets/Cables/Mid-Voltage/Cores/7/7mm.png'),
          '10mm': require('./../assets/Cables/Mid-Voltage/Cores/7/16mm.png'),
        },
      },
    },
    'Wires': {
      'Cores' : {
        '1' : {
          '1mm': require('./../assets/Cables/Wires/Cores/1/1mm.png'),
          '1.5mm': require('./../assets/Cables/Wires/Cores/1/4mm.png'),
          '2mm': require('./../assets/Cables/Wires/Cores/1/7mm.png'),
          '4mm': require('./../assets/Cables/Wires/Cores/1/16mm.png'),
          '6mm': require('./../assets/Cables/Wires/Cores/1/1mm.png'),
          '10mm': require('./../assets/Cables/Wires/Cores/1/4mm.png'),
          '16mm': require('./../assets/Cables/Wires/Cores/1/7mm.png'),
          '25mm': require('./../assets/Cables/Wires/Cores/1/16mm.png'),
          '35mm': require('./../assets/Cables/Wires/Cores/1/1mm.png'),
          '50mm': require('./../assets/Cables/Wires/Cores/1/4mm.png'),
          '70mm': require('./../assets/Cables/Wires/Cores/1/7mm.png'),
        },
        '2' : {
          '1mm': require('./../assets/Cables/Wires/Cores/2/1mm.png'),
          '1.5mm': require('./../assets/Cables/Wires/Cores/2/4mm.png'),
          '2mm': require('./../assets/Cables/Wires/Cores/2/7mm.png'),
          '4mm': require('./../assets/Cables/Wires/Cores/2/16mm.png'),
          '6mm': require('./../assets/Cables/Wires/Cores/2/1mm.png'),
          '10mm': require('./../assets/Cables/Wires/Cores/2/4mm.png'),
          '16mm': require('./../assets/Cables/Wires/Cores/2/7mm.png'),
          '25mm': require('./../assets/Cables/Wires/Cores/2/16mm.png'),
          '35mm': require('./../assets/Cables/Wires/Cores/2/1mm.png'),
          '50mm': require('./../assets/Cables/Wires/Cores/2/4mm.png'),
          '70mm': require('./../assets/Cables/Wires/Cores/2/7mm.png'),
        },
        '3' : {
          '1mm': require('./../assets/Cables/Wires/Cores/3/1mm.png'),
          '1.5mm': require('./../assets/Cables/Wires/Cores/3/4mm.png'),
          '2mm': require('./../assets/Cables/Wires/Cores/3/7mm.png'),
          '4mm': require('./../assets/Cables/Wires/Cores/3/16mm.png'),
          '6mm': require('./../assets/Cables/Wires/Cores/3/1mm.png'),
          '10mm': require('./../assets/Cables/Wires/Cores/3/4mm.png'),
          '16mm': require('./../assets/Cables/Wires/Cores/3/7mm.png'),
          '25mm': require('./../assets/Cables/Wires/Cores/3/16mm.png'),
          '35mm': require('./../assets/Cables/Wires/Cores/3/1mm.png'),
          '50mm': require('./../assets/Cables/Wires/Cores/3/4mm.png'),
          '70mm': require('./../assets/Cables/Wires/Cores/3/7mm.png'),
        },
        '4' : {
          '10mm': require('./../assets/Cables/Wires/Cores/4/4mm.png'),
          '16mm': require('./../assets/Cables/Wires/Cores/4/7mm.png'),
          '25mm': require('./../assets/Cables/Wires/Cores/4/16mm.png'),
          '35mm': require('./../assets/Cables/Wires/Cores/4/1mm.png'),
          '50mm': require('./../assets/Cables/Wires/Cores/4/4mm.png'),
          '70mm': require('./../assets/Cables/Wires/Cores/4/7mm.png'),
          '95mm': require('./../assets/Cables/Wires/Cores/4/16mm.png'),
          '120mm': require('./../assets/Cables/Wires/Cores/4/1mm.png'),
          '150mm': require('./../assets/Cables/Wires/Cores/4/4mm.png'),
          '185mm': require('./../assets/Cables/Wires/Cores/4/7mm.png'),
        },
        '5' : {
          '2mm': require('./../assets/Cables/Wires/Cores/5/4mm.png'),
          '4mm': require('./../assets/Cables/Wires/Cores/5/7mm.png'),
          '6mm': require('./../assets/Cables/Wires/Cores/5/16mm.png'),
          '10mm': require('./../assets/Cables/Wires/Cores/5/1mm.png'),
          '16mm': require('./../assets/Cables/Wires/Cores/5/4mm.png'),
          '25mm': require('./../assets/Cables/Wires/Cores/5/7mm.png'),
          '35mm': require('./../assets/Cables/Wires/Cores/5/16mm.png'),
          '50mm': require('./../assets/Cables/Wires/Cores/5/1mm.png'),
          '70mm': require('./../assets/Cables/Wires/Cores/5/4mm.png'),
          '95mm': require('./../assets/Cables/Wires/Cores/5/7mm.png'),
          '120mm': require('./../assets/Cables/Wires/Cores/5/1mm.png'),
        },
        '6' : {
          '1mm': require('./../assets/Cables/Wires/Cores/6/1mm.png'),
          '1.5mm': require('./../assets/Cables/Wires/Cores/6/4mm.png'),
          '2mm': require('./../assets/Cables/Wires/Cores/6/7mm.png'),
          '4mm': require('./../assets/Cables/Wires/Cores/6/16mm.png'),
          '6mm': require('./../assets/Cables/Wires/Cores/6/7mm.png'),
          '10mm': require('./../assets/Cables/Wires/Cores/6/16mm.png'),
        },
        '7' : {
          '1mm': require('./../assets/Cables/Wires/Cores/7/1mm.png'),
          '1.5mm': require('./../assets/Cables/Wires/Cores/7/4mm.png'),
          '2mm': require('./../assets/Cables/Wires/Cores/7/7mm.png'),
          '4mm': require('./../assets/Cables/Wires/Cores/7/16mm.png'),
          '6mm': require('./../assets/Cables/Wires/Cores/7/7mm.png'),
          '10mm': require('./../assets/Cables/Wires/Cores/7/16mm.png'),
        },
      },
      // Add suboptions for 'Wires' here
      '1mm': require('./../assets/Cables/Wires/1mm.png'),
      '4mm': require('./../assets/Cables/Wires/4mm.png'),
      '7mm': require('./../assets/Cables/Wires/7mm.png'),
      '16mm': require('./../assets/Cables/Wires/16mm.png'),
    },
  };

